name: ctrdecrypt build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux-x86_64
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
          - os: macos-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build release
      run:
        cargo build --release
    - if: ${{ matrix.os }} != 'windows-latest'
      run:
        strip target/release/${{ matrix.artifact_name }}
    - name: Upload artifacts
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/${{ matrix.artifact_name}}